language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cppcheck

os:
  - linux

before_install:
  - set -e

before_script:
  - cd squashfs-tools

script:
  - make

after_success:
  - if type cppcheck &> /dev/null ; then cppcheck --error-exitcode=1 --quiet *.h *.c squashfs-tools/ ; fi
